/**
 * Firing intervals and placing shots inside them.
 *
 * THE IDEA TURNED AROUND. Previously the flash FILTERED audio candidates: each one asked
 * "is there a flash in my window". Both problems came from that at once — one flash said
 * "yes" to five neighbours, and a shot whose flash fell between frames got no answer from
 * anyone.
 *
 * Here the flash BOUNDS AN INTERVAL ("the player fired from 3.05 to 3.40"), and the shots
 * inside are generated by the weapon's rhythm. The number of shots is COUNTED, not guessed:
 * interval length divided by the period, plus one.
 *
 * WHY THIS IS ALLOWED. Measurement showed individual shots cannot be told apart on the flash
 * curve — in a burst it burns continuously and does not dip between shots. But the rate is
 * set by the weapon, and there are only twelve possible rates.
 *
 * THE COST OF ERROR DIFFERS, and the scheme accounts for it. Inside a burst an extra or
 * missing shot is inaudible after sound replacement, so the grid fills in boldly there.
 * A single shot is heard in full — no grid is built for it, and the old path works:
 * the frame picks the nearest candidate, and a dispute between two candidates is settled by audio.
 */
import { FASTEST_PERIOD_S, FIRE_PERIODS_S, FIT_TOLERANCE_S } from './fireRates'

/** A stretch where the model sees a flash. */
export interface FlashInterval {
  start: number
  end: number
  /** Time of the most confident frame of the stretch. */
  peak: number
  /** Confidence on that frame. */
  score: number
  /**
   * How many SEPARATE flashes are inside the stretch: continuous runs of hot frames
   * separated by cold ones.
   *
   * This is a lower bound on the shot count, and it is needed as insurance against a grid
   * out of nothing. A single AWP flash burns three frames in a row, i.e. 67 ms; a grid with
   * a 120 ms period gave `round(0.067/0.12) + 1 = 2` nodes on it and doubled a single shot.
   */
  runs: number
}

/** A shot moment generated by the grid. */
export interface Placed {
  time: number
  /** Period of the grid that generated the shot, seconds. `null` — a single shot, no grid. */
  period: number | null
  /** Flash confidence on the interval the shot came from. */
  score: number
  /** The shot was filled in by the grid: audio heard it, but there is no flash in the frames. */
  filled: boolean
}

/**
 * What share of grid nodes must rest on an audio candidate for the grid to be trusted.
 *
 * Not one: audio merges some shots of a burst, and demanding support under every node means
 * rejecting correct grids. Not a half: any period satisfies a weak requirement.
 */
const MIN_GRID_SUPPORT = 0.6

/**
 * What an EMPTY grid node is worth, in units of audio confidence.
 *
 * The reward for a supported node is the audio confidence under it, zero to one. The penalty
 * for an empty one must be measured the same way. A typical confirmed candidate's confidence
 * is about 0.8, so an empty node costs roughly one supported one.
 */
const AVERAGE_STRENGTH = 0.8

/**
 * Node tolerance as a FRACTION OF THE PERIOD, not a constant.
 *
 * A fixed 25 ms ruined the whole search: at a 70 ms period that is over a third of a step,
 * and audio candidates come every 46 ms — something was found under every node of a dense
 * grid, and it beat the correct one under any scoring, by head count or by weight.
 * A fraction of the period levels the grids: each one's window is proportional to its step.
 */
const NODE_TOLERANCE_FRACTION = 0.15

/**
 * The gap by which hot frames merge into ONE firing stretch.
 *
 * An interval here is not "one flash" but "the player fired from here to here". The
 * difference is fundamental: PP-Bizon shots come every 80 ms, i.e. every two to three frames,
 * and the flash does not burn on each of them. By frame adjacency such flashes broke into
 * fifty stretches of one shot each, and the grid had nothing to build on.
 *
 * 250 ms is longer than the inter-shot interval of any automatic weapon in the game
 * (the slowest automatic is the CZ75, 100 ms) and shorter than a typical pause between
 * bursts.
 */
const FIRING_GAP_S = 0.25

/** Group hot frames into stretches. The curve does not dip between frames of a burst. */
export function findIntervals(
  frames: { time: number; score: number }[],
  threshold: number,
): FlashInterval[] {
  const hot = frames.filter((f) => f.score >= threshold).sort((a, b) => a.time - b.time)
  if (!hot.length) return []

  // The frame step comes from the data itself: the corpus has both 30 and 60 fps.
  const steps = frames
    .map((f, i) => (i ? f.time - frames[i - 1].time : 0))
    .filter((d) => d > 0.001)
    .sort((a, b) => a - b)
  const step = steps.length ? steps[Math.floor(steps.length / 2)] : 1 / 30

  const out: FlashInterval[] = []
  let group = [hot[0]]
  const flush = () => {
    const best = group.reduce((a, b) => (b.score > a.score ? b : a))
    // Separate flashes inside the stretch: a gap longer than a frame with a small margin.
    let runs = 1
    for (let i = 1; i < group.length; i++) {
      if (group[i].time - group[i - 1].time > step * 1.5) runs++
    }
    out.push({
      start: group[0].time,
      end: group[group.length - 1].time,
      peak: best.time,
      score: best.score,
      runs,
    })
  }
  for (const frame of hot.slice(1)) {
    if (frame.time - group[group.length - 1].time <= Math.max(step * 1.5, FIRING_GAP_S)) group.push(frame)
    else {
      flush()
      group = [frame]
    }
  }
  flush()
  return out
}

/**
 * Place shots on an interval.
 *
 * TWO TIME SCALES, and they must not be confused. The interval lives on the FRAME clock,
 * candidates on the AUDIO clock, and audio in these clips lags the picture by 100-200 ms,
 * differently for each clip. The first version looked for candidates inside the interval and
 * found none: they lie to the right. So the interval is first moved onto the audio clock by
 * the same window the candidates used to look for their frames.
 *
 * The grid is built on the AUDIO clock and must pass through a heard shot: it is anchored to
 * a candidate, not to the interval boundary. The node count is taken from the interval length
 * — the picture knows it, and it is an honest estimate of the firing duration.
 *
 * @param window frame search window, [back, forward] in seconds — the same as the stage's
 */
export function placeShots(
  interval: FlashInterval,
  candidates: { time: number; strength: number }[],
  window: [number, number],
  /** Period read from the picture. If given, only the phase is searched on audio. */
  forced: number | null = null,
): Placed[] | null {
  const tol = FIT_TOLERANCE_S
  const [back, forward] = window
  // A candidate could have produced a frame of this interval if the interval fell into its window.
  const lo = interval.start - forward
  const hi = interval.end - back
  const inside = candidates
    .filter((c) => c.time >= lo - tol && c.time <= hi + tol)
    .sort((a, b) => a.time - b.time)
  if (!inside.length) return null

  // ONE FLASH — ONE SHOT, there is nothing to build a grid from. Without this check a single
  // AWP shot (flash over three consecutive frames, 67 ms) was doubled by a 120 ms grid.
  if (interval.runs < 2) return null

  const span = interval.end - interval.start
  let best: { period: number; nodes: number[]; support: number; fit: number } | null = null

  // If the period is known from the picture, only the phase is searched on audio. That is
  // stronger: there are two pieces of evidence, and they are independent.
  const periods = forced !== null ? [forced] : FIRE_PERIODS_S
  for (const period of periods) {
    // A whole period must fit into the stretch. The old `round(span / period) + 1` gave
    // two nodes already at span of half a period — i.e. on a single flash.
    if (span < period) continue
    const count = Math.round(span / period) + 1
    const nodeTol = Math.min(tol, NODE_TOLERANCE_FRACTION * period)
    for (const anchor of inside) {
      // A grid of count nodes passing through the candidate: all positions of the anchor
      // inside it are tried.
      for (let first = 0; first < count; first++) {
        const nodes: number[] = []
        for (let k = 0; k < count; k++) nodes.push(anchor.time + (k - first) * period)
        if (nodes[0] < lo - tol || nodes[nodes.length - 1] > hi + tol) continue
        // A node weighs AS MUCH as the audio under it is confident, not one. A dense grid
        // rests on weak candidates — echoes and tails — and won over the correct one by head
        // count; by weight it loses.
        let weight = 0
        let support = 0
        for (const node of nodes) {
          let best = 0
          for (const c of inside) {
            if (Math.abs(c.time - node) <= nodeTol && c.strength > best) best = c.strength
          }
          if (best > 0) {
            support++
            weight += best
          }
        }
        // Empty nodes are PENALISED. Neither the share nor the absolute count works on its
        // own, and both extremes were tested: by share the coarsest grid wins (three nodes are
        // always 100% supported, and a burst of thirty-five shots was labelled with three
        // marks), by absolute count the finest wins (there are three times more candidates
        // than shots, and a dense grid finds support by chance: ak47 came out at 857 rpm
        // instead of 600).
        //
        // The difference "supported minus empty" balances both: the coarse grid loses on its
        // small node count, the fine one on its gaps.
        // An empty node is penalised by the weight of an AVERAGE candidate, not one: otherwise
        // penalty and reward are measured in different units.
        const fit = 2 * weight - count * AVERAGE_STRENGTH
        if (!best || fit > best.fit || (fit === best.fit && period > best.period)) {
          best = { period, nodes, support, fit }
        }
      }
    }
  }

  // No grid, or it hangs by a thread — THE GRID IS NOT FORCED, null is returned. The caller
  // handles it, and that is not laziness: for a single shot there is already a working path —
  // the "frame picks the nearest candidate" assignment with disputes settled by audio. It
  // cannot be reproduced here, the interval does not remember which frame picked whom, and an
  // attempt to replace it with "the loudest in the window" put the label on a neighbour
  // (0.697 instead of 0.639) and lost the shot.
  if (!best || best.support / best.nodes.length < MIN_GRID_SUPPORT) return null

  const out: Placed[] = []
  for (const node of best.nodes) {
    let near: { time: number; strength: number } | null = null
    let distance = tol
    for (const c of inside) {
      const d = Math.abs(c.time - node)
      if (d < distance) {
        distance = d
        near = c
      }
    }
    // The moment comes from audio: its grid is three times finer than a video frame. A node
    // without audio we fill in ourselves — the flash said the player was firing.
    out.push({ time: near ? near.time : node, period: best.period, score: interval.score, filled: !near })
  }
  return out
}

/**
 * Weapon period FROM THE PICTURE: from the distances between brightness-excess peaks.
 *
 * TESTED AND NOT USED IN THE PRODUCT. The idea was strong: audio gives three times more
 * candidates than shots, and a dense grid finds support by chance, while there are exactly
 * as many brightness peaks as flashes. The evidence is independent, and the audio lag does
 * not hurt it — the period is computed from distances between peaks on a single clock.
 *
 * It broke on frame rate. At 30 fps a weapon firing 750 rounds per minute fires once every
 * 2.4 frames, and there is simply no separate local maximum per shot — the peaks alias in
 * frequency. The estimate comes out as a MULTIPLE of the true one:
 *
 *   bizon   spec 750 -> got 400 (half as fast)
 *   ak47    spec 600 -> got 500
 *   aug     spec 666 -> got 500
 *
 * Substituting this period into placement made things worse: bizon went from 48 labels at the
 * correct rate of 750 down to 38 labels and 400.
 *
 * The function is kept as a tool: the brightness-excess series itself has structure that the
 * model confidence lacks (that one is binary), and a 60 fps recording will not alias.
 * Profile measurement — `python/tools/flash_profile.py`.
 */
export function periodFromBrightness(
  frames: { time: number; excess: number }[],
  tolerance = FIT_TOLERANCE_S,
): number | null {
  const peaks: number[] = []
  for (let i = 1; i < frames.length - 1; i++) {
    const { excess } = frames[i]
    // A local maximum and clearly above its neighbours: a plateau inside a long flash is not a peak.
    if (excess <= frames[i - 1].excess || excess < frames[i + 1].excess) continue
    if (peaks.length && frames[i].time - peaks[peaks.length - 1] < FASTEST_PERIOD_S) continue
    peaks.push(frames[i].time)
  }
  if (peaks.length < 3) return null

  const gaps: number[] = []
  for (let i = 1; i < peaks.length; i++) gaps.push(peaks[i] - peaks[i - 1])

  // From coarse period to fine, the first one that explains most gaps. Order matters:
  // anything fits a fine grid.
  for (const period of FIRE_PERIODS_S) {
    let fit = 0
    for (const gap of gaps) {
      const k = Math.round(gap / period)
      if (k >= 1 && Math.abs(gap - k * period) <= tolerance) fit++
    }
    if (fit >= Math.ceil(0.6 * gaps.length)) return period
  }
  return null
}

/**
 * Another way to place shots inside an interval: WITHOUT A GRID, with plain non-maximum
 * suppression on audio.
 *
 * The idea is simpler than the current one and removes its main weakness. Currently the burst
 * period is fitted to audio candidates, and there are three times more of them than shots, so
 * a dense grid gathers support by chance: `ak47` came out at 857 rounds per minute instead of
 * the spec 600. Here no period is needed at all — the flash said "a burst is happening here",
 * and how many bullets are in it is counted by audio.
 *
 * Difference from the rejected "whole burst" scheme: there ALL candidates were taken in a row,
 * and precision fell to 36%. Here the fire-rate limit is kept between labels.
 */
export function placeByAudioPeaks(
  interval: FlashInterval,
  candidates: { time: number; strength: number }[],
  window: [number, number],
  minGap: number,
): Placed[] | null {
  const [back, forward] = window
  const inside = candidates.filter(
    (c) => c.time >= interval.start - forward && c.time <= interval.end - back,
  )
  if (!inside.length) return null

  // Non-maximum suppression: the strongest by audio takes its place and kills neighbours
  // within the fire-rate limit.
  const kept: { time: number; strength: number }[] = []
  for (const c of [...inside].sort((a, b) => b.strength - a.strength)) {
    if (kept.some((k) => Math.abs(k.time - c.time) < minGap)) continue
    kept.push(c)
  }
  return kept
    .sort((a, b) => a.time - b.time)
    .map((c) => ({ time: c.time, period: null, score: interval.score, filled: false }))
}
